name: CRON Compiler

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  compiler:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: current
    - run: npm i -g @adguard/hostlist-compiler
    - run: hostlist-compiler -c hostlist-compiler-config.json -o filters/full.txt
    - run: npm install -g @quilicicf/markdown-formatter
    - run: markdown-format -f README.md -o README.md
    - run: |
        curl https://big.oisd.nl -o filters/big.oisd.txt
        curl https://secure.fanboy.co.nz/fanboy-cookiemonster.txt -o filters/fanboy-cookiemonster.txt
        curl https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser -o filters/CoinBlockerLists.txt
        curl https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt -o filters/adblock-nocoin-list.txt
        curl https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt -o filters/abpvn.txt
        curl https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts -o filters/hostsvn.txt
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "auto: `full.txt` updated at $(date +'%Y-%m-%d %H:%M:%S')"
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

